### ISSUE TITLE
Event loop continues if JSON from kafka is non-parseable?

### ISSUE THREAD

**Issue by MrCreosote** [kbase/index_runner_deluxe#125]
Based on https://github.com/kbase/index_runner_deluxe/blob/develop/src/index_runner/main.py#L112-L121, it appears that if the JSON received from Kafka is unparseable, the event loop will log a message but keep going as if nothing is wrong, and `_handle_msg` will be called with the `Message` class returned from the kafka client rather than a dict unmarshalled from the JSON as expected.

**Comment by jayrbolton** [comment]
Ah yes, another good point. We definitely meant to `raise err` on the catch.

**Comment by jayrbolton** [comment]
Rather, a `continue` makes more sense.

**Comment by MrCreosote** [comment]
If you just continue I think you'll just get the same message again right?

**Comment by jayrbolton** [comment]
Good catch again, added consumer.commit() above the continue, see PR above
