### ISSUE TITLE
Health check for writer threads

### ISSUE THREAD

**Issue by scanon** [kbase/index_runner_deluxe#86]
If all the writer threads die then the worker will still continue to process requests but nothing gets written.  There should be some health check and the whole worker should probably die if the workers threads fail.

**Comment by jayrbolton** [comment]
I think the issue was that the es_writer workers were raising an error on every single job it performed due to ES incompatibility. The threads will never actually die, as the WorkerGroup class will catch every exception, print it, and the thread will continue

**Comment by jayrbolton** [comment]
I think we figured out that it was the parent process that was crashing when it can't fetch the github config. Or maybe a combination of this and the above. Fixed in #91
